db_file: "bot.db"

bot_url: "https://t.me/Eckorezze_Bot"
auth_server_url: "http://localhost/"
messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в твоём Pocket-аккаунте, тебе нужно дать разрешение. Для этого перейди по ссылке:\n%s"
    already_authorized: "Вы уже авторизированны. Присылайте ссылку и я сохраняю её."
    link_saved: "Ссылка успешно сохранена!"
    unknown_command: "Я не знаю такой команды!"
  errors:
    default: "Произошла неизвестная ошибка."
    invalid_url: "Это невалидная ссылка!"
    unauthorized: "Вы не авторизованы! Используйте команду /start"
    unable_to_save: "Не удалось сохранить ссылку. Повторите попытку ещё раз позже."
